version: {{TASK_VERSION}}
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: {{TASK_DEFINITION_ARN}}
        LoadBalancerInfo:
          ContainerName: {{CONTAINER_NAME}}
          ContainerPort: {{CONTAINER_PORT}}