name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and push detected changes
        id: build-image
        uses: ./.github/actions/build_image
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
      aws_region: ${{ vars.AWS_REGION }}
      aws_role: ${{ vars.AWS_ROLE }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.aws_region }}
            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
            role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
            cd tf
            terraform init
    
      - name: Deploy
        shell: bash
        id: deploy
        env:
          TF_VAR_project_name: ${{ github.event.repository.name }}
          TF_VAR_image_uri: ${{ needs.build.outputs.image_uri }}
        run: |
            cd tf
            terraform apply -auto-approve
