name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
  aws_region: ${{ vars.AWS_REGION }}
  aws_role: ${{ vars.AWS_ROLE }}

permissions:
  id-token: write
  contents: read
      
jobs:
  deploy-ecr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.aws_region }}
            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
            role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
            cd tf-ecr
            terraform init
    
      - name: Deploy
        shell: bash
        id: deploy
        env:
          TF_VAR_project_name: ${{ github.event.repository.name }}
        run: |
            cd tf-ecr
            terraform apply -auto-approve

  build:
    needs: deploy-ecr
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.aws_region }}
            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
            role-session-name: GitHubActions

      - name: Build and push detected changes
        id: build-image
        uses: ./.github/actions/build_image
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_region: ${{ vars.AWS_REGION }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ env.aws_region }}
            role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
            role-session-name: GitHubActions

      # - name: Init
      #   shell: bash
      #   run: |
      #       cd tf
      #       terraform init
    
      # - name: Deploy
      #   shell: bash
      #   id: deploy
      #   env:
      #     TF_VAR_project_name: ${{ github.event.repository.name }}
      #     TF_VAR_image_uri: ${{ needs.build.outputs.image_uri }}
      #   run: |
      #       cd tf
      #       terraform apply -auto-approve
