name: Destroy

on:
  workflow_dispatch:
  workflow_call:

env:
  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
  aws_region: ${{ vars.AWS_REGION }}
  aws_role: ${{ vars.AWS_ROLE }}

  TF_VAR_project_name: ${{ github.event.repository.name }}
  TF_VAR_region: ${{ vars.AWS_REGION }}
  TF_VAR_private_vpc_name: ecs-private-vpc
  TF_VAR_api_stage_name: dev
  TF_VAR_container_port: 3000
  TF_VAR_load_balancer_port: 80

permissions:
  id-token: write
  contents: read
      
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/task
          terraform init
    
      - name: Destroy
        shell: bash
        id: destroy
        run: |
          cd tf/task
          terraform destroy -auto-approve

  ecr:
    needs: task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/ecr
          terraform init
    
      - name: Destroy
        shell: bash
        id: destroy
        run: |
          cd tf/ecr
          terraform destroy -auto-approve

  service:
    runs-on: ubuntu-latest
    env:
      TF_VAR_task_definition_arn: dummy
      TF_VAR_private_vpc_id: dummy
      TF_VAR_private_subnet_ids: "[]"
      TF_VAR_lb_target_group_arn: dummy
      TF_VAR_load_balancer_security_group_id: dummy
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/service
          terraform init
    
      - name: Destroy
        shell: bash
        id: destroy
        run: |
          cd tf/service
          terraform destroy -auto-approve

  network:
    runs-on: ubuntu-latest
    needs: service
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        shell: bash
        run: |
          cd tf/network
          terraform init
    
      - name: Destroy
        shell: bash
        id: destroy
        run: |
          cd tf/network
          terraform destroy -auto-approve

